name: "Email and Password Test"
on: 
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  #make sure that the action works on the test firebase project using email and password
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with: 
          credentials: ${{ secrets.FIREBASE_CRED }}
          config: ${{ secrets.FIREBASE_EMAIL_AND_PASSWORD_USERS }}
